spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8083
resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 5
        wait-duration: 5s
    metrics:
      legacy:
        enabled: true
      enabled: true